export * from './activityLogs.service';
import { ActivityLogsService } from './activityLogs.service';
export * from './anonymousExchanges.service';
import { AnonymousExchangesService } from './anonymousExchanges.service';
export * from './apiSocket.service';
import { ApiSocketService } from './apiSocket.service';
export * from './appRights.service';
import { AppRightsService } from './appRights.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './candidateApplications.service';
import { CandidateApplicationsService } from './candidateApplications.service';
export * from './candidateJobOfferHistory.service';
import { CandidateJobOfferHistoryService } from './candidateJobOfferHistory.service';
export * from './candidateMessages.service';
import { CandidateMessagesService } from './candidateMessages.service';
export * from './candidatePresentations.service';
import { CandidatePresentationsService } from './candidatePresentations.service';
export * from './candidateResumes.service';
import { CandidateResumesService } from './candidateResumes.service';
export * from './candidates.service';
import { CandidatesService } from './candidates.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './gdrive.service';
import { GdriveService } from './gdrive.service';
export * from './history.service';
import { HistoryService } from './history.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './interviews.service';
import { InterviewsService } from './interviews.service';
export * from './jobOffers.service';
import { JobOffersService } from './jobOffers.service';
export * from './jobReferences.service';
import { JobReferencesService } from './jobReferences.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './keyValue.service';
import { KeyValueService } from './keyValue.service';
export * from './mail.service';
import { MailService } from './mail.service';
export * from './newsletter.service';
import { NewsletterService } from './newsletter.service';
export * from './newsletterTemplates.service';
import { NewsletterTemplatesService } from './newsletterTemplates.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './pdf.service';
import { PdfService } from './pdf.service';
export * from './referential.service';
import { ReferentialService } from './referential.service';
export * from './translate.service';
import { TranslateService } from './translate.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './usersRoles.service';
import { UsersRolesService } from './usersRoles.service';
export const APIS = [ActivityLogsService, AnonymousExchangesService, ApiSocketService, AppRightsService, AuthService, CandidateApplicationsService, CandidateJobOfferHistoryService, CandidateMessagesService, CandidatePresentationsService, CandidateResumesService, CandidatesService, CustomersService, DefaultService, FileService, GdriveService, HistoryService, ImageService, InterviewsService, JobOffersService, JobReferencesService, JobsService, KeyValueService, MailService, NewsletterService, NewsletterTemplatesService, NotificationsService, PdfService, ReferentialService, TranslateService, UsersService, UsersRolesService];
