/**
 * Node Angular App Template
 * Node Angular App Template API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetUserConnectionsResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ApiSocketServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * getSocketConnections
     * 
     */
    getSocketConnections(extraHttpRequestParams?: any): Observable<GetUserConnectionsResponse>;

}
