/**
 * Node Angular App Template
 * Node Angular App Template API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BackToOriginalRequest } from '../model/models';
import { GenericResponse } from '../model/models';
import { LogAsRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { LoginViewModel } from '../model/models';
import { RegisterRequest } from '../model/models';
import { SendRecoverPasswordMailRequest } from '../model/models';
import { SocialLoginRequest } from '../model/models';
import { UpdateUserPasswordRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * backToOriginalRequester
     * 
     * @param backToOriginalRequest 
     */
    backToOriginalRequester(backToOriginalRequest: BackToOriginalRequest, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * Update user password
     * 
     * @param updateUserPasswordRequest 
     */
    changeUserPasswordFromRecoverToken(updateUserPasswordRequest: UpdateUserPasswordRequest, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * get-updated-access-token
     * 
     */
    getUpdatedAccessToken(extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * logAs
     * 
     * @param logAsRequest 
     */
    logAs(logAsRequest: LogAsRequest, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * Login user
     * 
     * @param loginViewModel 
     */
    login(loginViewModel: LoginViewModel, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * refresh token
     * 
     */
    refreshToken(extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * register
     * 
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * Send recover password mail
     * 
     * @param sendRecoverPasswordMailRequest 
     */
    sendRecoverPasswordMail(sendRecoverPasswordMailRequest: SendRecoverPasswordMailRequest, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * register
     * 
     * @param socialLoginRequest 
     */
    socialLogin(socialLoginRequest: SocialLoginRequest, extraHttpRequestParams?: any): Observable<GenericResponse>;

}
