/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { ApplyToJobOffersRequest } from '../model/models';
import { GenericResponse } from '../model/models';
import { GetCandidateApplicationResponse } from '../model/models';
import { GetCandidateApplicationsResponse } from '../model/models';
import { GetJobOffersResponse } from '../model/models';
import { GuidExchangeResponse } from '../model/models';
import { IpAllowedResponse } from '../model/models';
import { RefuseCandidateApplicationRequest } from '../model/models';
import { SetCandidateApplicationUnseenRequest } from '../model/models';
import { SubmitCandidateApplicationFormRequest } from '../model/models';
import { UnSeenCandidateApplicationResponse } from '../model/models';
import { ValidateCandidateApplicationRequest } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface ApplyToJobOffersRequestParams {
    applyToJobOffersRequest: ApplyToJobOffersRequest;
}

export interface ArchiveCandidateApplicationsRequestParams {
    requestBody: Array<string>;
}

export interface CreateOrUpdateCandidateApplicationRequestParams {
    submitCandidateApplicationFormRequest: SubmitCandidateApplicationFormRequest;
}

export interface CreateOrUpdateRefCandidateApplicationRequestParams {
    submitCandidateApplicationFormRequest: SubmitCandidateApplicationFormRequest;
}

export interface DeleteCandidateApplicationsRequestParams {
    ids: string;
}

export interface GenerateGuidExchangeAndSendEmailRequestParams {
    id: string;
}

export interface GetAllCandidateApplicationsRequestParams {
    /** The start of the request */
    start?: number;
    /** The length of the request */
    length?: number;
    /** order by field */
    orderby?: string;
    /** order direction (asc | desc) */
    order?: string;
    /** Search */
    search?: string;
    /** select candidates-applications with status selected */
    applyStatus?: string;
    /** select candidates-applications with status selected */
    candidateStatus?: string;
    /** select candidates-applications with relationship selected */
    applyInCouple?: string;
    /** select candidates-applications with job offer reference */
    jobOfferRef?: string;
    /** select candidates-applications with job category */
    jobCategory?: string;
    /** select candidates-applications with candidate id */
    candidateId?: string;
    /** filter by status archive or not */
    disabled?: string;
    /** filter by status archive or not */
    includeDisabled?: string;
    /** filter by seen or not */
    showOnlyUnSeen?: string;
    /** filter spontxsaneous application */
    spontaneousApplication?: string;
    /** hide spontaneous applications */
    hideSpontaneousApplications?: string;
    /** filter only new candidates (not linked to existing candidate) */
    onlyNewCandidate?: string;
    /** filter by consultant */
    consultantIds?: string;
    /** select candidates-applications with job offer id */
    jobOfferId?: string;
    /** Exclude placed candidate */
    excludePlaced?: string;
    /** Filter by city (comma-separated list) */
    city?: string;
    /** Filter by country codes (comma-separated list) */
    locations?: string;
    /** Filter by department */
    department?: string;
}

export interface GetAllRecruitmentActivitiesRequestParams {
    /** The start of the request */
    start?: number;
    /** The length of the request */
    length?: number;
    /** order by field */
    orderby?: string;
    /** order direction (asc | desc) */
    order?: string;
    /** Search */
    search?: string;
    /** filter job offers by jobs */
    jobIds?: string;
    /** filter job offer by country code */
    countryCode?: string;
    /** filter job offer by consultant */
    consultantIds?: string;
    /** filter job offer with relationship selected */
    applyInCouple?: string;
    /** filter job by status archive or not */
    status?: string;
    /** filter by city */
    city?: string;
    /** filter by contractType */
    contractTypeId?: string;
    /** filter by customerIds */
    customerIds?: string;
    /** filter by contractTypeIds */
    contractTypeIds?: string;
    /** filter by stateId */
    stateId?: string;
    /** exclude job offers that already have candidates placed to them */
    excludePlacedJobOffers?: string;
}

export interface GetCandidateApplicationRequestParams {
    id: string;
}

export interface GetCandidateApplicationFromGuidRequestParams {
    guid: string;
}

export interface GetMyCandidateApplicationDetailRequestParams {
    id: string;
}

export interface GetMyCandidateApplicationsRequestParams {
    /** The start of the request */
    start?: number;
    /** The length of the request */
    length?: number;
    /** order by field */
    orderby?: string;
    /** order direction (asc | desc) */
    order?: string;
    /** Search */
    search?: string;
    /** select candidates-applications with status selected */
    applyStatus?: string;
    /** select candidates-applications with status selected */
    candidateStatus?: string;
    /** select candidates-applications with relationship selected */
    applyInCouple?: string;
    /** select candidates-applications with job offer reference */
    jobOfferRef?: string;
    /** select candidates-applications with job category */
    jobCategory?: string;
    /** select candidates-applications with candidate id */
    candidateId?: string;
    /** filter by status archive or not */
    disabled?: string;
    /** filter by status archive or not */
    includeDisabled?: string;
    /** filter by seen or not */
    showOnlyUnSeen?: string;
    /** filter spontxsaneous application */
    spontaneousApplication?: string;
    /** hide spontaneous applications */
    hideSpontaneousApplications?: string;
    /** filter only new candidates (not linked to existing candidate) */
    onlyNewCandidate?: string;
    /** filter by consultant */
    consultantIds?: string;
    /** select candidates-applications with job offer id */
    jobOfferId?: string;
    /** Exclude placed candidate */
    excludePlaced?: string;
    /** Filter by city (comma-separated list) */
    city?: string;
    /** Filter by country codes (comma-separated list) */
    locations?: string;
    /** Filter by department */
    department?: string;
}

export interface LinkCandidateApplicationToCandidateFromMailRequestParams {
    id: string;
}

export interface RefuseCandidateApplicationRequestParams {
    refuseCandidateApplicationRequest: RefuseCandidateApplicationRequest;
}

export interface SendMailAfterCandidateApplicationRefusedRequestParams {
    type: string;
    id: string;
}

export interface SendPositionFilledEmailRequestParams {
    /** The start of the request */
    start?: number;
    /** The length of the request */
    length?: number;
    /** order by field */
    orderby?: string;
    /** order direction (asc | desc) */
    order?: string;
    /** Search */
    search?: string;
    /** select candidates-applications with status selected */
    applyStatus?: string;
    /** select candidates-applications with status selected */
    candidateStatus?: string;
    /** select candidates-applications with relationship selected */
    applyInCouple?: string;
    /** select candidates-applications with job offer reference */
    jobOfferRef?: string;
    /** select candidates-applications with job category */
    jobCategory?: string;
    /** select candidates-applications with candidate id */
    candidateId?: string;
    /** filter by status archive or not */
    disabled?: string;
    /** filter by status archive or not */
    includeDisabled?: string;
    /** filter by seen or not */
    showOnlyUnSeen?: string;
    /** filter spontxsaneous application */
    spontaneousApplication?: string;
    /** hide spontaneous applications */
    hideSpontaneousApplications?: string;
    /** filter only new candidates (not linked to existing candidate) */
    onlyNewCandidate?: string;
    /** filter by consultant */
    consultantIds?: string;
    /** select candidates-applications with job offer id */
    jobOfferId?: string;
    /** Exclude placed candidate */
    excludePlaced?: string;
    /** Filter by city (comma-separated list) */
    city?: string;
    /** Filter by country codes (comma-separated list) */
    locations?: string;
    /** Filter by department */
    department?: string;
}

export interface SendPrivateExchangeLinkToCandidateApplicationRequestParams {
    id: string;
}

export interface SetCandidateApplicationSeenRequestParams {
    id: string;
}

export interface SetCandidateApplicationUnseenRequestParams {
    setCandidateApplicationUnseenRequest: SetCandidateApplicationUnseenRequest;
}

export interface ValidateCandidateApplicationRequestParams {
    validateCandidateApplicationRequest: ValidateCandidateApplicationRequest;
}


@Injectable({
  providedIn: 'root'
})
export class CandidateApplicationsService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * applyToJobOffers
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public applyToJobOffers(requestParameters: ApplyToJobOffersRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public applyToJobOffers(requestParameters: ApplyToJobOffersRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public applyToJobOffers(requestParameters: ApplyToJobOffersRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public applyToJobOffers(requestParameters: ApplyToJobOffersRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const applyToJobOffersRequest = requestParameters.applyToJobOffersRequest;
        if (applyToJobOffersRequest === null || applyToJobOffersRequest === undefined) {
            throw new Error('Required parameter applyToJobOffersRequest was null or undefined when calling applyToJobOffers.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/applyToJobOffers`,
            applyToJobOffersRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Archive candidate applications
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public archiveCandidateApplications(requestParameters: ArchiveCandidateApplicationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public archiveCandidateApplications(requestParameters: ArchiveCandidateApplicationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public archiveCandidateApplications(requestParameters: ArchiveCandidateApplicationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public archiveCandidateApplications(requestParameters: ArchiveCandidateApplicationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const requestBody = requestParameters.requestBody;
        if (requestBody === null || requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling archiveCandidateApplications.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/archiveCandidateApplication`,
            requestBody,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create or update candidate application
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createOrUpdateCandidateApplication(requestParameters: CreateOrUpdateCandidateApplicationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public createOrUpdateCandidateApplication(requestParameters: CreateOrUpdateCandidateApplicationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public createOrUpdateCandidateApplication(requestParameters: CreateOrUpdateCandidateApplicationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public createOrUpdateCandidateApplication(requestParameters: CreateOrUpdateCandidateApplicationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const submitCandidateApplicationFormRequest = requestParameters.submitCandidateApplicationFormRequest;
        if (submitCandidateApplicationFormRequest === null || submitCandidateApplicationFormRequest === undefined) {
            throw new Error('Required parameter submitCandidateApplicationFormRequest was null or undefined when calling createOrUpdateCandidateApplication.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications`,
            submitCandidateApplicationFormRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create candidate application from ref
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createOrUpdateRefCandidateApplication(requestParameters: CreateOrUpdateRefCandidateApplicationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public createOrUpdateRefCandidateApplication(requestParameters: CreateOrUpdateRefCandidateApplicationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public createOrUpdateRefCandidateApplication(requestParameters: CreateOrUpdateRefCandidateApplicationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public createOrUpdateRefCandidateApplication(requestParameters: CreateOrUpdateRefCandidateApplicationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const submitCandidateApplicationFormRequest = requestParameters.submitCandidateApplicationFormRequest;
        if (submitCandidateApplicationFormRequest === null || submitCandidateApplicationFormRequest === undefined) {
            throw new Error('Required parameter submitCandidateApplicationFormRequest was null or undefined when calling createOrUpdateRefCandidateApplication.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/candidate/createOrUpdateRefCandidateApplication`,
            submitCandidateApplicationFormRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete candidate applications
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCandidateApplications(requestParameters: DeleteCandidateApplicationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public deleteCandidateApplications(requestParameters: DeleteCandidateApplicationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public deleteCandidateApplications(requestParameters: DeleteCandidateApplicationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public deleteCandidateApplications(requestParameters: DeleteCandidateApplicationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const ids = requestParameters.ids;
        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling deleteCandidateApplications.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/${encodeURIComponent(String(ids))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * generateGuidExchangeAndSendEmail
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generateGuidExchangeAndSendEmail(requestParameters: GenerateGuidExchangeAndSendEmailRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GuidExchangeResponse>;
    public generateGuidExchangeAndSendEmail(requestParameters: GenerateGuidExchangeAndSendEmailRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GuidExchangeResponse>>;
    public generateGuidExchangeAndSendEmail(requestParameters: GenerateGuidExchangeAndSendEmailRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GuidExchangeResponse>>;
    public generateGuidExchangeAndSendEmail(requestParameters: GenerateGuidExchangeAndSendEmailRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling generateGuidExchangeAndSendEmail.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GuidExchangeResponse>(`${this.configuration.basePath}/api/candidate-applications/generateGuidExchangeAndSendEmail/${encodeURIComponent(String(id))}`,
            null,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all candidate applications
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllCandidateApplications(requestParameters: GetAllCandidateApplicationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationsResponse>;
    public getAllCandidateApplications(requestParameters: GetAllCandidateApplicationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationsResponse>>;
    public getAllCandidateApplications(requestParameters: GetAllCandidateApplicationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationsResponse>>;
    public getAllCandidateApplications(requestParameters: GetAllCandidateApplicationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const start = requestParameters.start;
        const length = requestParameters.length;
        const orderby = requestParameters.orderby;
        const order = requestParameters.order;
        const search = requestParameters.search;
        const applyStatus = requestParameters.applyStatus;
        const candidateStatus = requestParameters.candidateStatus;
        const applyInCouple = requestParameters.applyInCouple;
        const jobOfferRef = requestParameters.jobOfferRef;
        const jobCategory = requestParameters.jobCategory;
        const candidateId = requestParameters.candidateId;
        const disabled = requestParameters.disabled;
        const includeDisabled = requestParameters.includeDisabled;
        const showOnlyUnSeen = requestParameters.showOnlyUnSeen;
        const spontaneousApplication = requestParameters.spontaneousApplication;
        const hideSpontaneousApplications = requestParameters.hideSpontaneousApplications;
        const onlyNewCandidate = requestParameters.onlyNewCandidate;
        const consultantIds = requestParameters.consultantIds;
        const jobOfferId = requestParameters.jobOfferId;
        const excludePlaced = requestParameters.excludePlaced;
        const city = requestParameters.city;
        const locations = requestParameters.locations;
        const department = requestParameters.department;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (start !== undefined && start !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>start, 'start');
        }
        if (length !== undefined && length !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>length, 'length');
        }
        if (orderby !== undefined && orderby !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>orderby, 'orderby');
        }
        if (order !== undefined && order !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>order, 'order');
        }
        if (search !== undefined && search !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>search, 'search');
        }
        if (applyStatus !== undefined && applyStatus !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyStatus, 'applyStatus');
        }
        if (candidateStatus !== undefined && candidateStatus !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateStatus, 'candidateStatus');
        }
        if (applyInCouple !== undefined && applyInCouple !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyInCouple, 'applyInCouple');
        }
        if (jobOfferRef !== undefined && jobOfferRef !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferRef, 'jobOfferRef');
        }
        if (jobCategory !== undefined && jobCategory !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobCategory, 'jobCategory');
        }
        if (candidateId !== undefined && candidateId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateId, 'candidateId');
        }
        if (disabled !== undefined && disabled !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>disabled, 'disabled');
        }
        if (includeDisabled !== undefined && includeDisabled !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>includeDisabled, 'includeDisabled');
        }
        if (showOnlyUnSeen !== undefined && showOnlyUnSeen !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>showOnlyUnSeen, 'showOnlyUnSeen');
        }
        if (spontaneousApplication !== undefined && spontaneousApplication !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>spontaneousApplication, 'spontaneousApplication');
        }
        if (hideSpontaneousApplications !== undefined && hideSpontaneousApplications !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>hideSpontaneousApplications, 'hideSpontaneousApplications');
        }
        if (onlyNewCandidate !== undefined && onlyNewCandidate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>onlyNewCandidate, 'onlyNewCandidate');
        }
        if (consultantIds !== undefined && consultantIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>consultantIds, 'consultantIds');
        }
        if (jobOfferId !== undefined && jobOfferId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferId, 'jobOfferId');
        }
        if (excludePlaced !== undefined && excludePlaced !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>excludePlaced, 'excludePlaced');
        }
        if (city !== undefined && city !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>city, 'city');
        }
        if (locations !== undefined && locations !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>locations, 'locations');
        }
        if (department !== undefined && department !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>department, 'department');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetCandidateApplicationsResponse>(`${this.configuration.basePath}/api/candidate-applications`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all Recruitment Activities
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllRecruitmentActivities(requestParameters: GetAllRecruitmentActivitiesRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetJobOffersResponse>;
    public getAllRecruitmentActivities(requestParameters: GetAllRecruitmentActivitiesRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetJobOffersResponse>>;
    public getAllRecruitmentActivities(requestParameters: GetAllRecruitmentActivitiesRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetJobOffersResponse>>;
    public getAllRecruitmentActivities(requestParameters: GetAllRecruitmentActivitiesRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const start = requestParameters.start;
        const length = requestParameters.length;
        const orderby = requestParameters.orderby;
        const order = requestParameters.order;
        const search = requestParameters.search;
        const jobIds = requestParameters.jobIds;
        const countryCode = requestParameters.countryCode;
        const consultantIds = requestParameters.consultantIds;
        const applyInCouple = requestParameters.applyInCouple;
        const status = requestParameters.status;
        const city = requestParameters.city;
        const contractTypeId = requestParameters.contractTypeId;
        const customerIds = requestParameters.customerIds;
        const contractTypeIds = requestParameters.contractTypeIds;
        const stateId = requestParameters.stateId;
        const excludePlacedJobOffers = requestParameters.excludePlacedJobOffers;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (start !== undefined && start !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>start, 'start');
        }
        if (length !== undefined && length !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>length, 'length');
        }
        if (orderby !== undefined && orderby !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>orderby, 'orderby');
        }
        if (order !== undefined && order !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>order, 'order');
        }
        if (search !== undefined && search !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>search, 'search');
        }
        if (jobIds !== undefined && jobIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobIds, 'jobIds');
        }
        if (countryCode !== undefined && countryCode !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>countryCode, 'countryCode');
        }
        if (consultantIds !== undefined && consultantIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>consultantIds, 'consultantIds');
        }
        if (applyInCouple !== undefined && applyInCouple !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyInCouple, 'applyInCouple');
        }
        if (status !== undefined && status !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>status, 'status');
        }
        if (city !== undefined && city !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>city, 'city');
        }
        if (contractTypeId !== undefined && contractTypeId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>contractTypeId, 'contractTypeId');
        }
        if (customerIds !== undefined && customerIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>customerIds, 'customerIds');
        }
        if (contractTypeIds !== undefined && contractTypeIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>contractTypeIds, 'contractTypeIds');
        }
        if (stateId !== undefined && stateId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>stateId, 'stateId');
        }
        if (excludePlacedJobOffers !== undefined && excludePlacedJobOffers !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>excludePlacedJobOffers, 'excludePlacedJobOffers');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetJobOffersResponse>(`${this.configuration.basePath}/api/candidate-applications/getAllRecruitmentActivities`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get candidate application
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCandidateApplication(requestParameters: GetCandidateApplicationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public getCandidateApplication(requestParameters: GetCandidateApplicationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public getCandidateApplication(requestParameters: GetCandidateApplicationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public getCandidateApplication(requestParameters: GetCandidateApplicationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getCandidateApplication.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/get/${encodeURIComponent(String(id))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get candidate application from guid
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCandidateApplicationFromGuid(requestParameters: GetCandidateApplicationFromGuidRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public getCandidateApplicationFromGuid(requestParameters: GetCandidateApplicationFromGuidRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public getCandidateApplicationFromGuid(requestParameters: GetCandidateApplicationFromGuidRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public getCandidateApplicationFromGuid(requestParameters: GetCandidateApplicationFromGuidRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const guid = requestParameters.guid;
        if (guid === null || guid === undefined) {
            throw new Error('Required parameter guid was null or undefined when calling getCandidateApplicationFromGuid.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/getCandidateApplicationFromGuid/${encodeURIComponent(String(guid))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get candidate application detail of the current user
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMyCandidateApplicationDetail(requestParameters: GetMyCandidateApplicationDetailRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public getMyCandidateApplicationDetail(requestParameters: GetMyCandidateApplicationDetailRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public getMyCandidateApplicationDetail(requestParameters: GetMyCandidateApplicationDetailRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public getMyCandidateApplicationDetail(requestParameters: GetMyCandidateApplicationDetailRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getMyCandidateApplicationDetail.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/getMyCandidateApplicationDetail/${encodeURIComponent(String(id))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get candidate applications of the current user
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMyCandidateApplications(requestParameters: GetMyCandidateApplicationsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationsResponse>;
    public getMyCandidateApplications(requestParameters: GetMyCandidateApplicationsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationsResponse>>;
    public getMyCandidateApplications(requestParameters: GetMyCandidateApplicationsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationsResponse>>;
    public getMyCandidateApplications(requestParameters: GetMyCandidateApplicationsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const start = requestParameters.start;
        const length = requestParameters.length;
        const orderby = requestParameters.orderby;
        const order = requestParameters.order;
        const search = requestParameters.search;
        const applyStatus = requestParameters.applyStatus;
        const candidateStatus = requestParameters.candidateStatus;
        const applyInCouple = requestParameters.applyInCouple;
        const jobOfferRef = requestParameters.jobOfferRef;
        const jobCategory = requestParameters.jobCategory;
        const candidateId = requestParameters.candidateId;
        const disabled = requestParameters.disabled;
        const includeDisabled = requestParameters.includeDisabled;
        const showOnlyUnSeen = requestParameters.showOnlyUnSeen;
        const spontaneousApplication = requestParameters.spontaneousApplication;
        const hideSpontaneousApplications = requestParameters.hideSpontaneousApplications;
        const onlyNewCandidate = requestParameters.onlyNewCandidate;
        const consultantIds = requestParameters.consultantIds;
        const jobOfferId = requestParameters.jobOfferId;
        const excludePlaced = requestParameters.excludePlaced;
        const city = requestParameters.city;
        const locations = requestParameters.locations;
        const department = requestParameters.department;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (start !== undefined && start !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>start, 'start');
        }
        if (length !== undefined && length !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>length, 'length');
        }
        if (orderby !== undefined && orderby !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>orderby, 'orderby');
        }
        if (order !== undefined && order !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>order, 'order');
        }
        if (search !== undefined && search !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>search, 'search');
        }
        if (applyStatus !== undefined && applyStatus !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyStatus, 'applyStatus');
        }
        if (candidateStatus !== undefined && candidateStatus !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateStatus, 'candidateStatus');
        }
        if (applyInCouple !== undefined && applyInCouple !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyInCouple, 'applyInCouple');
        }
        if (jobOfferRef !== undefined && jobOfferRef !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferRef, 'jobOfferRef');
        }
        if (jobCategory !== undefined && jobCategory !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobCategory, 'jobCategory');
        }
        if (candidateId !== undefined && candidateId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateId, 'candidateId');
        }
        if (disabled !== undefined && disabled !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>disabled, 'disabled');
        }
        if (includeDisabled !== undefined && includeDisabled !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>includeDisabled, 'includeDisabled');
        }
        if (showOnlyUnSeen !== undefined && showOnlyUnSeen !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>showOnlyUnSeen, 'showOnlyUnSeen');
        }
        if (spontaneousApplication !== undefined && spontaneousApplication !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>spontaneousApplication, 'spontaneousApplication');
        }
        if (hideSpontaneousApplications !== undefined && hideSpontaneousApplications !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>hideSpontaneousApplications, 'hideSpontaneousApplications');
        }
        if (onlyNewCandidate !== undefined && onlyNewCandidate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>onlyNewCandidate, 'onlyNewCandidate');
        }
        if (consultantIds !== undefined && consultantIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>consultantIds, 'consultantIds');
        }
        if (jobOfferId !== undefined && jobOfferId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferId, 'jobOfferId');
        }
        if (excludePlaced !== undefined && excludePlaced !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>excludePlaced, 'excludePlaced');
        }
        if (city !== undefined && city !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>city, 'city');
        }
        if (locations !== undefined && locations !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>locations, 'locations');
        }
        if (department !== undefined && department !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>department, 'department');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetCandidateApplicationsResponse>(`${this.configuration.basePath}/api/candidate-applications/getMyCandidateApplications`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get unseen candidate application number
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUnSeenCandidateApplications(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<UnSeenCandidateApplicationResponse>;
    public getUnSeenCandidateApplications(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<UnSeenCandidateApplicationResponse>>;
    public getUnSeenCandidateApplications(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<UnSeenCandidateApplicationResponse>>;
    public getUnSeenCandidateApplications(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<UnSeenCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/infos/getUnSeenCandidateApplications`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * isCountryAllowed
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public isCountryAllowed(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<IpAllowedResponse>;
    public isCountryAllowed(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<IpAllowedResponse>>;
    public isCountryAllowed(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<IpAllowedResponse>>;
    public isCountryAllowed(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<IpAllowedResponse>(`${this.configuration.basePath}/api/candidate-applications/isCountryAllowed`,
            null,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * linkCandidateApplicationToCandidateFromMail
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public linkCandidateApplicationToCandidateFromMail(requestParameters: LinkCandidateApplicationToCandidateFromMailRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public linkCandidateApplicationToCandidateFromMail(requestParameters: LinkCandidateApplicationToCandidateFromMailRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public linkCandidateApplicationToCandidateFromMail(requestParameters: LinkCandidateApplicationToCandidateFromMailRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public linkCandidateApplicationToCandidateFromMail(requestParameters: LinkCandidateApplicationToCandidateFromMailRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling linkCandidateApplicationToCandidateFromMail.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (id !== undefined && id !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>id, 'id');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/linkCandidateApplicationToCandidateFromMail`,
            null,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Refuse candidate application and create candidate
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public refuseCandidateApplication(requestParameters: RefuseCandidateApplicationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public refuseCandidateApplication(requestParameters: RefuseCandidateApplicationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public refuseCandidateApplication(requestParameters: RefuseCandidateApplicationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public refuseCandidateApplication(requestParameters: RefuseCandidateApplicationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const refuseCandidateApplicationRequest = requestParameters.refuseCandidateApplicationRequest;
        if (refuseCandidateApplicationRequest === null || refuseCandidateApplicationRequest === undefined) {
            throw new Error('Required parameter refuseCandidateApplicationRequest was null or undefined when calling refuseCandidateApplication.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/refuseAndCreateCandidate`,
            refuseCandidateApplicationRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * sendMailAfterCandidateApplicationRefused
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendMailAfterCandidateApplicationRefused(requestParameters: SendMailAfterCandidateApplicationRefusedRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public sendMailAfterCandidateApplicationRefused(requestParameters: SendMailAfterCandidateApplicationRefusedRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public sendMailAfterCandidateApplicationRefused(requestParameters: SendMailAfterCandidateApplicationRefusedRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public sendMailAfterCandidateApplicationRefused(requestParameters: SendMailAfterCandidateApplicationRefusedRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const type = requestParameters.type;
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling sendMailAfterCandidateApplicationRefused.');
        }
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling sendMailAfterCandidateApplicationRefused.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (type !== undefined && type !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>type, 'type');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/sendMailAfterCandidateApplicationRefused/${encodeURIComponent(String(id))}`,
            null,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send position is filled email
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendPositionFilledEmail(requestParameters: SendPositionFilledEmailRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationsResponse>;
    public sendPositionFilledEmail(requestParameters: SendPositionFilledEmailRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationsResponse>>;
    public sendPositionFilledEmail(requestParameters: SendPositionFilledEmailRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationsResponse>>;
    public sendPositionFilledEmail(requestParameters: SendPositionFilledEmailRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const start = requestParameters.start;
        const length = requestParameters.length;
        const orderby = requestParameters.orderby;
        const order = requestParameters.order;
        const search = requestParameters.search;
        const applyStatus = requestParameters.applyStatus;
        const candidateStatus = requestParameters.candidateStatus;
        const applyInCouple = requestParameters.applyInCouple;
        const jobOfferRef = requestParameters.jobOfferRef;
        const jobCategory = requestParameters.jobCategory;
        const candidateId = requestParameters.candidateId;
        const disabled = requestParameters.disabled;
        const includeDisabled = requestParameters.includeDisabled;
        const showOnlyUnSeen = requestParameters.showOnlyUnSeen;
        const spontaneousApplication = requestParameters.spontaneousApplication;
        const hideSpontaneousApplications = requestParameters.hideSpontaneousApplications;
        const onlyNewCandidate = requestParameters.onlyNewCandidate;
        const consultantIds = requestParameters.consultantIds;
        const jobOfferId = requestParameters.jobOfferId;
        const excludePlaced = requestParameters.excludePlaced;
        const city = requestParameters.city;
        const locations = requestParameters.locations;
        const department = requestParameters.department;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (start !== undefined && start !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>start, 'start');
        }
        if (length !== undefined && length !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>length, 'length');
        }
        if (orderby !== undefined && orderby !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>orderby, 'orderby');
        }
        if (order !== undefined && order !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>order, 'order');
        }
        if (search !== undefined && search !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>search, 'search');
        }
        if (applyStatus !== undefined && applyStatus !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyStatus, 'applyStatus');
        }
        if (candidateStatus !== undefined && candidateStatus !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateStatus, 'candidateStatus');
        }
        if (applyInCouple !== undefined && applyInCouple !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>applyInCouple, 'applyInCouple');
        }
        if (jobOfferRef !== undefined && jobOfferRef !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferRef, 'jobOfferRef');
        }
        if (jobCategory !== undefined && jobCategory !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobCategory, 'jobCategory');
        }
        if (candidateId !== undefined && candidateId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateId, 'candidateId');
        }
        if (disabled !== undefined && disabled !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>disabled, 'disabled');
        }
        if (includeDisabled !== undefined && includeDisabled !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>includeDisabled, 'includeDisabled');
        }
        if (showOnlyUnSeen !== undefined && showOnlyUnSeen !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>showOnlyUnSeen, 'showOnlyUnSeen');
        }
        if (spontaneousApplication !== undefined && spontaneousApplication !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>spontaneousApplication, 'spontaneousApplication');
        }
        if (hideSpontaneousApplications !== undefined && hideSpontaneousApplications !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>hideSpontaneousApplications, 'hideSpontaneousApplications');
        }
        if (onlyNewCandidate !== undefined && onlyNewCandidate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>onlyNewCandidate, 'onlyNewCandidate');
        }
        if (consultantIds !== undefined && consultantIds !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>consultantIds, 'consultantIds');
        }
        if (jobOfferId !== undefined && jobOfferId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferId, 'jobOfferId');
        }
        if (excludePlaced !== undefined && excludePlaced !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>excludePlaced, 'excludePlaced');
        }
        if (city !== undefined && city !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>city, 'city');
        }
        if (locations !== undefined && locations !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>locations, 'locations');
        }
        if (department !== undefined && department !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>department, 'department');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<GetCandidateApplicationsResponse>(`${this.configuration.basePath}/api/candidate-applications/sendPositionFilledEmail`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * sendPrivateExchangeLinkToCandidateApplication
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendPrivateExchangeLinkToCandidateApplication(requestParameters: SendPrivateExchangeLinkToCandidateApplicationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public sendPrivateExchangeLinkToCandidateApplication(requestParameters: SendPrivateExchangeLinkToCandidateApplicationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public sendPrivateExchangeLinkToCandidateApplication(requestParameters: SendPrivateExchangeLinkToCandidateApplicationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public sendPrivateExchangeLinkToCandidateApplication(requestParameters: SendPrivateExchangeLinkToCandidateApplicationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling sendPrivateExchangeLinkToCandidateApplication.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/sendPrivateExchangeLinkToCandidateApplication/${encodeURIComponent(String(id))}`,
            null,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * set candidate application as seen
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setCandidateApplicationSeen(requestParameters: SetCandidateApplicationSeenRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public setCandidateApplicationSeen(requestParameters: SetCandidateApplicationSeenRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public setCandidateApplicationSeen(requestParameters: SetCandidateApplicationSeenRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public setCandidateApplicationSeen(requestParameters: SetCandidateApplicationSeenRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const id = requestParameters.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling setCandidateApplicationSeen.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/infos/setCandidateApplicationSeen/${encodeURIComponent(String(id))}`,
            null,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * setCandidateApplicationUnseen
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setCandidateApplicationUnseen(requestParameters: SetCandidateApplicationUnseenRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GenericResponse>;
    public setCandidateApplicationUnseen(requestParameters: SetCandidateApplicationUnseenRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GenericResponse>>;
    public setCandidateApplicationUnseen(requestParameters: SetCandidateApplicationUnseenRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GenericResponse>>;
    public setCandidateApplicationUnseen(requestParameters: SetCandidateApplicationUnseenRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const setCandidateApplicationUnseenRequest = requestParameters.setCandidateApplicationUnseenRequest;
        if (setCandidateApplicationUnseenRequest === null || setCandidateApplicationUnseenRequest === undefined) {
            throw new Error('Required parameter setCandidateApplicationUnseenRequest was null or undefined when calling setCandidateApplicationUnseen.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GenericResponse>(`${this.configuration.basePath}/api/candidate-applications/setCandidateApplicationUnseen`,
            setCandidateApplicationUnseenRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Validate candidate application and create candidate
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validateCandidateApplication(requestParameters: ValidateCandidateApplicationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<GetCandidateApplicationResponse>;
    public validateCandidateApplication(requestParameters: ValidateCandidateApplicationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<GetCandidateApplicationResponse>>;
    public validateCandidateApplication(requestParameters: ValidateCandidateApplicationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<GetCandidateApplicationResponse>>;
    public validateCandidateApplication(requestParameters: ValidateCandidateApplicationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        const validateCandidateApplicationRequest = requestParameters.validateCandidateApplicationRequest;
        if (validateCandidateApplicationRequest === null || validateCandidateApplicationRequest === undefined) {
            throw new Error('Required parameter validateCandidateApplicationRequest was null or undefined when calling validateCandidateApplication.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<GetCandidateApplicationResponse>(`${this.configuration.basePath}/api/candidate-applications/validateAndCreateCandidate`,
            validateCandidateApplicationRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
