/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { CreateCandidateJobOfferHistoryRequest } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface CandidateJobOfferHistoryControllerCreateHistoryEntryRequestParams {
    createCandidateJobOfferHistoryRequest: CreateCandidateJobOfferHistoryRequest;
}

export interface CandidateJobOfferHistoryControllerGetCandidateHistoryRequestParams {
    candidateId: string;
    jobOfferId?: string;
    candidateId2?: string;
    start?: number;
    length?: number;
    orderby?: string;
    order?: string;
}

export interface CandidateJobOfferHistoryControllerGetJobOfferHistoryRequestParams {
    jobOfferId: string;
    jobOfferId2?: string;
    candidateId?: string;
    start?: number;
    length?: number;
    orderby?: string;
    order?: string;
}


@Injectable({
  providedIn: 'root'
})
export class CandidateJobOfferHistoryService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Create a new history entry
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public candidateJobOfferHistoryControllerCreateHistoryEntry(requestParameters: CandidateJobOfferHistoryControllerCreateHistoryEntryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public candidateJobOfferHistoryControllerCreateHistoryEntry(requestParameters: CandidateJobOfferHistoryControllerCreateHistoryEntryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public candidateJobOfferHistoryControllerCreateHistoryEntry(requestParameters: CandidateJobOfferHistoryControllerCreateHistoryEntryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public candidateJobOfferHistoryControllerCreateHistoryEntry(requestParameters: CandidateJobOfferHistoryControllerCreateHistoryEntryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        const createCandidateJobOfferHistoryRequest = requestParameters.createCandidateJobOfferHistoryRequest;
        if (createCandidateJobOfferHistoryRequest === null || createCandidateJobOfferHistoryRequest === undefined) {
            throw new Error('Required parameter createCandidateJobOfferHistoryRequest was null or undefined when calling candidateJobOfferHistoryControllerCreateHistoryEntry.');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<any>(`${this.configuration.basePath}/api/candidate-job-offer-history`,
            createCandidateJobOfferHistoryRequest,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get history for a specific candidate
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public candidateJobOfferHistoryControllerGetCandidateHistory(requestParameters: CandidateJobOfferHistoryControllerGetCandidateHistoryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public candidateJobOfferHistoryControllerGetCandidateHistory(requestParameters: CandidateJobOfferHistoryControllerGetCandidateHistoryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public candidateJobOfferHistoryControllerGetCandidateHistory(requestParameters: CandidateJobOfferHistoryControllerGetCandidateHistoryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public candidateJobOfferHistoryControllerGetCandidateHistory(requestParameters: CandidateJobOfferHistoryControllerGetCandidateHistoryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        const candidateId = requestParameters.candidateId;
        if (candidateId === null || candidateId === undefined) {
            throw new Error('Required parameter candidateId was null or undefined when calling candidateJobOfferHistoryControllerGetCandidateHistory.');
        }
        const jobOfferId = requestParameters.jobOfferId;
        const candidateId2 = requestParameters.candidateId2;
        const start = requestParameters.start;
        const length = requestParameters.length;
        const orderby = requestParameters.orderby;
        const order = requestParameters.order;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (jobOfferId !== undefined && jobOfferId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferId, 'jobOfferId');
        }
        if (candidateId2 !== undefined && candidateId2 !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateId2, 'candidateId');
        }
        if (start !== undefined && start !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>start, 'start');
        }
        if (length !== undefined && length !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>length, 'length');
        }
        if (orderby !== undefined && orderby !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>orderby, 'orderby');
        }
        if (order !== undefined && order !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>order, 'order');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/api/candidate-job-offer-history/candidate/${encodeURIComponent(String(candidateId))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get history for a specific job offer
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public candidateJobOfferHistoryControllerGetJobOfferHistory(requestParameters: CandidateJobOfferHistoryControllerGetJobOfferHistoryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public candidateJobOfferHistoryControllerGetJobOfferHistory(requestParameters: CandidateJobOfferHistoryControllerGetJobOfferHistoryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public candidateJobOfferHistoryControllerGetJobOfferHistory(requestParameters: CandidateJobOfferHistoryControllerGetJobOfferHistoryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public candidateJobOfferHistoryControllerGetJobOfferHistory(requestParameters: CandidateJobOfferHistoryControllerGetJobOfferHistoryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        const jobOfferId = requestParameters.jobOfferId;
        if (jobOfferId === null || jobOfferId === undefined) {
            throw new Error('Required parameter jobOfferId was null or undefined when calling candidateJobOfferHistoryControllerGetJobOfferHistory.');
        }
        const jobOfferId2 = requestParameters.jobOfferId2;
        const candidateId = requestParameters.candidateId;
        const start = requestParameters.start;
        const length = requestParameters.length;
        const orderby = requestParameters.orderby;
        const order = requestParameters.order;

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (jobOfferId2 !== undefined && jobOfferId2 !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>jobOfferId2, 'jobOfferId');
        }
        if (candidateId !== undefined && candidateId !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>candidateId, 'candidateId');
        }
        if (start !== undefined && start !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>start, 'start');
        }
        if (length !== undefined && length !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>length, 'length');
        }
        if (orderby !== undefined && orderby !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>orderby, 'orderby');
        }
        if (order !== undefined && order !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>order, 'order');
        }

        let headers = this.defaultHeaders;

        let credential: string | undefined;
        // authentication (bearer) required
        credential = this.configuration.lookupCredential('bearer');
        if (credential) {
            headers = headers.set('Authorization', 'Bearer ' + credential);
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/api/candidate-job-offer-history/job-offer/${encodeURIComponent(String(jobOfferId))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
