/**
 * Node Angular App Template
 * Node Angular App Template API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenericResponse } from '../model/models';
import { GetAppImageResponse } from '../model/models';
import { GetAppImagesResponse } from '../model/models';
import { ResizeAppImageRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ImageServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * deleteImages
     * 
     * @param ids 
     */
    deleteImages(ids: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * get all images
     * 
     * @param start The start of the request
     * @param length The length of the request
     * @param orderby order by field
     * @param order order direction (asc | desc)
     * @param search Search
     */
    getAllLibraryImages(start?: number, length?: number, orderby?: string, order?: string, search?: string, extraHttpRequestParams?: any): Observable<GetAppImagesResponse>;

    /**
     * resizeImage
     * 
     * @param resizeAppImageRequest 
     */
    resizeImage(resizeAppImageRequest: ResizeAppImageRequest, extraHttpRequestParams?: any): Observable<GetAppImageResponse>;

    /**
     * upload image
     * 
     */
    uploadImage(extraHttpRequestParams?: any): Observable<GetAppImageResponse>;

}
