/**
 * Node Angular App Template
 * Node Angular App Template API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenericResponse } from '../model/models';
import { GetJobResponse } from '../model/models';
import { GetJobsResponse } from '../model/models';
import { JobDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface JobsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create or update job
     * 
     * @param jobDto 
     */
    createOrUpdateJob(jobDto: JobDto, extraHttpRequestParams?: any): Observable<GetJobResponse>;

    /**
     * Delete job
     * 
     * @param jobIds 
     */
    deleteJobs(jobIds: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * Get all jobs
     * 
     * @param start The start of the request
     * @param length The length of the request
     * @param orderby order by field
     * @param order order direction (asc | desc)
     * @param search Search
     */
    getAllJobs(start?: number, length?: number, orderby?: string, order?: string, search?: string, extraHttpRequestParams?: any): Observable<GetJobsResponse>;

    /**
     * Get job
     * 
     * @param jobId 
     * @param includeJobHistory 
     */
    getJob(jobId: string, includeJobHistory?: string, extraHttpRequestParams?: any): Observable<GetJobResponse>;

    /**
     * Trigger job
     * 
     * @param id 
     */
    triggerJob(id: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

}
