/**
 * Node Angular App Template
 * Node Angular App Template API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenericResponse } from '../model/models';
import { PushSubscriptionDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface NotificationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * savePushSubscription
     * 
     * @param pushSubscriptionDto 
     */
    savePushSubscription(pushSubscriptionDto: PushSubscriptionDto, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * sendEventTest
     * 
     * @param userId 
     */
    sendEventTest(userId: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * sendEventTestSocket
     * 
     * @param userId 
     * @param fromFirebase 
     */
    sendEventTestSocket(userId: string, fromFirebase: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * sendNotificationTest
     * 
     * @param userId 
     */
    sendNotificationTest(userId: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

}
