/**
 * Node Angular App Template
 * Node Angular App Template API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenericResponse } from '../model/models';
import { GetUserResponse } from '../model/models';
import { GetUsersResponse } from '../model/models';
import { UserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create or update user
     * 
     * @param userDto 
     */
    createOrUpdateUser(userDto: UserDto, extraHttpRequestParams?: any): Observable<GetUserResponse>;

    /**
     * Delete user
     * 
     * @param userIds 
     */
    deleteUsers(userIds: string, extraHttpRequestParams?: any): Observable<GenericResponse>;

    /**
     * Get all users
     * 
     * @param start The start of the request
     * @param length The length of the request
     * @param orderby order by field
     * @param order order direction (asc | desc)
     * @param search Search
     */
    getAllUsers(start?: number, length?: number, orderby?: string, order?: string, search?: string, extraHttpRequestParams?: any): Observable<GetUsersResponse>;

    /**
     * Get user
     * 
     * @param userName 
     */
    getUser(userName: string, extraHttpRequestParams?: any): Observable<GetUserResponse>;

}
