/* eslint-disable quote-props */
export const JobsAssociationCRM = {
    "Animal carer": "jobcategory_dogsitter",
    "Art keeper": "jobcategory_gestionnaire-collection-art-prive",
    "Babysitter": "jobcategory_babysitter",
    "Base données": "", //Non trouvé
    "Bodyguard": "jobcategory_garde-du-corps",
    "Bodyguard / security manager ": "jobcategory_chef-de-la-securite",
    "Bosun": "jobcategory_skipper-equipage-de-yacht-voilier",
    "Butler": "jobcategory_majordome-maitre-d-hotel-huissier",
    "Cabin crew ": "jobcategory_skipper-equipage-de-yacht-voilier",
    "Candidats 2": "", //Non trouvé
    "Candidatures interessantes": "", //Non trouvé
    "Caregiver": "jobcategory_auxiliaire-de-vie-dame-de-compagnie",
    "Cars keeper": "jobcategory_gestionnaire-collection-automobile-prive",
    "Chauffeur": "jobcategory_chauffeur-de-maitre",
    "Chef": "jobcategory_chef-cuisinier",
    "Chef / cook": "jobcategory_chef-cuisinier",
    "Chief Steward": "jobcategory_hotesse-stewart-jet-prive",
    "Cleaner": "jobcategory_femme-de-menage-de-chambre",
    "Coach sportif": "jobcategory_coach-sportif",
    "Companion": "jobcategory_auxiliaire-de-vie-dame-de-compagnie",
    //TODO : changer ce métier
    // "Construction/Project Manager": "jobyachtingcategory_manager-de-projet-yacht",
    "Cook": "jobcategory_chef-cuisinier",
    "Deckland": "jobyachtingcategory_matelot-deckhand",
    "Deckhand": "jobyachtingcategory_matelot-deckhand",
    "Domestic": "jobcategory_couple-de-domestique",
    "Domestic couple": "jobcategory_couple-de-domestique",
    "Domestic employee": "jobcategory_couple-de-domestique",
    "Domestic Employee / Nanny": "jobnannycategory_nanny-employe-e-de-maison",
    "Estate Manager": "jobcategory_intendant-general-regisseur-house-manager",
    "Executive Assistant": "jobcategory_assistant-e-personnel-le-",
    "Executive chauffeur": "jobcategory_chauffeur-de-maitre",
    "Executive officer": "jobcategory_assistant-e-personnel-le-",
    "Facilities Manager": "jobcategory_homme-a-tout-faire",
    "Game keeper": "jobcategory_gardien-de-chasse",
    "Gardener": "jobcategory_jardinier",
    "Gardien": "jobcategory_couple-de-gardien",
    "Golf teacher": "jobcategory_professeur-de-golf",
    "Governess": "jobcategory_gouvernante",
    "Guardian": "jobcategory_garde-de-propriete",
    "Guardian couple": "jobcategory_couple-de-gardien",
    "H.m": "jobcategory_intendant-general-regisseur-house-manager",
    "Hairdresser": "jobcategory_coiffeur-personnel",
    "Hdtm": "jobcategory_homme-a-tout-faire",
    "Head housekeeper": "jobcategory_gouvernante",
    "Helicopter pilot": "jobcategory_pilote-d-helicoptere",
    "Horse Keeper": "jobcategory_gardien-de-propriete-equestre",
    "Hostess": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "Hostess/Receptionist": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "Hotel Butler": "jobcategory_majordome-maitre-d-hotel-huissier",
    "Hotel Executive Housekeeper": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "Hotel Finance": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "Hotel Housekeeper": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "Hotel Manager": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "Hotel staff": "jobcategory_personnel-et-employe-hotel-de-luxe-et-palace",
    "House Manager": "jobcategory_intendant-general-regisseur-house-manager",
    "House Manager / Estate manager": "jobcategory_intendant-general-regisseur-house-manager",
    "Housekeeper": "jobcategory_femme-de-menage-de-chambre",
    "Housekeeper / nanny / cook": "jobnannycategory_nanny-employe-e-de-maison",
    "Housekeper_nanny": "jobnannycategory_nanny-employe-e-de-maison",
    "Houseman": "jobcategory_homme-a-tout-faire",
    "Lady's Maid": "jobcategory_valet-de-chambre-groom",
    "Laundress": "jobcategory_femme-de-menage-de-chambre",
    "Maitre d'hotel": "jobcategory_majordome-maitre-d-hotel-huissier",
    "Make up artist": "jobcategory_personnel-de-massage-et-manucure",
    "Massage staff": "jobcategory_personnel-de-massage-et-manucure",
    "Maternity nurse": "jobcategory_assitante-maternelle-nourrice",
    "Moto chauffeur": "jobcategory_chauffeur-de-maitre",
    "Nanny": "jobnannycategory_nanny",
    "Not selected": "", //Non trouvé
    "Nutritionist": "jobcategory_nutritionniste",
    "Other": "jobcategory_autres",
    "P.a": "jobcategory_assistant-e-personnel-le-",
    "Palace Manager": "jobcategory_majordome-maitre-d-hotel-huissier",
    "Personal Assistant": "jobcategory_assistant-e-personnel-le-",
    "Personal assistant / secretary / family office": "jobcategory_assistant-e-personnel-le-",
    "Personal shopper": "jobcategory_personal-shopper",
    "Personal trainer / sports instructor": "jobcategory_coach-sportif",
    "Pilates": "jobcategory_professeur-de-yoga-pilate",
    "Private chauffeur": "jobcategory_chauffeur-de-maitre",
    "Private jet pilot": "jobcategory_pilote-de-jet-prive",
    "Property security officer": "jobcategory_chef-de-la-securite",
    "Purser": "jobyachtingcategory_capitaine-superyacht",
    "Purser/ Yacht Manager": "jobyachtingcategory_chef-executif-sur-yacht",
    "Purser/Yacht Manager": "jobyachtingcategory_chef-executif-sur-yacht",
    "Secretaire family office": "jobcategory_assistant-e-personnel-le-",
    "Secretary / Family Office": "jobcategory_assistant-e-personnel-le-",
    "Security officer": "jobcategory_chef-de-la-securite",
    "Ski teacher": "jobcategory_professeur-de-ski",
    "Skipper": "jobyachtingcategory_skipper",
    "Sommelier": "jobcategory_sommelier",
    "Spa/Beauty Staff": "jobyachtingcategory_personnel-de-beaute-sur-yacht",
    "Steward": "jobcategory_hotesse-stewart-jet-prive",
    "Tennis teacher": "jobcategory_professeur-de-tennis",
    "Tutor": "jobnannycategory_tuteur-tutrice",
    "Valet": "jobcategory_valet-de-chambre-groom",
    "Voiturier": "jobcategory_voiturier",
    "Yacht Beauty Staff": "jobyachtingcategory_personnel-de-beaute-sur-yacht",
    "Yacht Bodyguard": "jobyachtingcategory_garde-du-corps-sur-yacht",
    "Yacht Butler": "jobyachtingcategory_majordome-sur-yacht",
    "Yacht Captain": "jobyachtingcategory_capitaine-de-yacht",
    "Yacht Chef": "jobyachtingcategory_chef-cuisinier-sur-yacht",
    "Yacht Cook": "jobyachtingcategory_cuisinier-e-sur-yacht",
    "Yacht Couple": "jobyachtingcategory_couple-sur-yacht",
    "Yacht crew": "jobyachtingcategory_matelot-deckhand",
    "Yacht Diver": "jobyachtingcategory_plongeur-sur-yacht",
    "Yacht Engineer": "jobyachtingcategory_machiniste-mecanicien",
    "Yacht Helicopter Pilot": "jobyachtingcategory_pilote-helicoptere-yacht",
    "Yacht Interior Designer": "jobyachtingcategory_decorateur-architecte-d-interieur-yacht",
    "Yacht Laundress": "jobyachtingcategory_linger-e-sur-yacht",
    "Yacht Manager": "jobyachtingcategory_manager-gestionnaire-de-yacht",
    "Yacht Massage Staff": "jobyachtingcategory_personnel-de-massage-sur-yacht",
    "Yacht Nanny": "jobyachtingcategory_nannie-sur-yacht",
    "Yacht Officer/Mate": "jobyachtingcategory_officier-de-quart",
    "Yacht Project Manager": "jobyachtingcategory_manager-de-projet-yacht",
    "Yacht Sport Coach": "jobyachtingcategory_coach-personnel-yacht",
    "Yoga teacher": "jobcategory_professeur-de-yoga-pilate",
    "Watch officer": "jobyachtingcategory_officier-de-quart",
    "Cabin crew": "jobcategory_skipper-equipage-de-yacht-voilier",
};