#App Name
<VirtualHost *:80>
    ErrorLog /root/dev/logs/app-name/error.log
	CustomLog /root/dev/logs/app-name/access.log common
   	ServerName app-name.nextalys.com
	ServerAlias www.app-name.nextalys.com
	ServerAdmin contact@nextalys.com
    RewriteEngine on
	RewriteRule ^ https://app-name.nextalys.com [END,NE,R=permanent]
</VirtualHost>
<IfModule mod_ssl.c>
<VirtualHost *:443>
 	RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"
    
    ProxyPreserveHost On
   	ProxyPass / http://127.0.0.1:3020/
   	ProxyPassReverse / http://127.0.0.1:3020/
	ErrorLog /root/dev/logs/app-name/error.log
	CustomLog /root/dev/logs/app-name/access.log common
	ServerName app-name.nextalys.com
	ServerAlias www.app-name.com

	ServerAdmin contact@nextalys.com
    
	RewriteEngine on
	RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
	RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
	RewriteRule .* ws://localhost:3020%{REQUEST_URI} [P]

	#lines that follow redirect www to non www
	# RewriteEngine On
	# RewriteCond %{HTTP_HOST} ^www.qaou-gestion.nextalys.com [NC]
	# RewriteRule ^(.*)$ https://qaou-gestion.nextalys.com/$1 [L,R=301]


	SSLEngine On
	SSLCertificateFile /etc/letsencrypt/live/app-name.nextalys.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/app-name.nextalys.com/privkey.pem
</VirtualHost>
</IfModule>
