// Import your nationality data
const frenchNationalitiesMale = {
    AF: "Afghan",
    AL: "Albanais",
    DZ: "Algérien",
    AD: "Andorran",
    AO: "Angolais",
    AG: "Antiguayen",
    AR: "Argentin",
    AM: "Arménien",
    AU: "Australien",
    AT: "Autrichien",
    AZ: "Azerbaïdjanais",
    BS: "Bahamien",
    BH: "Bahreïnien",
    BD: "Bangladais",
    BB: "Barbadien",
    BY: "Biélorusse",
    BE: "Belge",
    BZ: "Bélizien",
    BJ: "Béninois",
    BM: "Bermudien",
    BT: "Bhoutanais",
    BO: "Bolivien",
    BA: "Bosnien",
    BW: "Botswanais",
    BR: "Brésilien",
    BN: "Brunéien",
    BG: "Bulgare",
    BF: "Burkinabé",
    BI: "Burundais",
    KH: "Cambodgien",
    CM: "Camerounais",
    CA: "Canadien",
    CV: "Cap verdien",
    KY: "Caïmanien",
    CF: "Centrafricain",
    TD: "Tchadien",
    CL: "Chilien",
    CN: "Chinois",
    CO: "Colombien",
    KM: "Comorien",
    CG: "Congolais (République du Congo)",
    CD: "Congolais (République démocratique du Congo)",
    CR: "Costaricain",
    CI: "Ivoirien",
    HR: "Croate",
    CU: "Cubain",
    CY: "Chypriote",
    CZ: "Tchèque",
    DK: "Danois",
    DJ: "Djiboutien",
    DM: "Dominicain (Dominique)",
    DO: "Dominicain (République dominicaine)",
    EC: "Équatorien",
    EG: "Égyptien",
    SV: "Salvadorien",
    GQ: "Équato-guinéen",
    ER: "Érythréen",
    EE: "Estonien",
    ET: "Éthiopien",
    FK: "Malouin",
    FO: "Féroïen",
    FJ: "Fidjien",
    FI: "Finlandais",
    FR: "Français",
    GF: "Français (Guyane)",
    PF: "Français (Polynésie française)",
    TF: "Français (TAAF)",
    GA: "Gabonais",
    GM: "Gambien",
    GE: "Géorgien",
    DE: "Allemand",
    GH: "Ghanéen",
    GI: "Gibraltariens",
    GR: "Grec",
    GL: "Groenlandais",
    GD: "Grenadien",
    GP: "Guadeloupéen",
    GT: "Guatémaltèque",
    GN: "Guinéen",
    GW: "Bissaoguinéen",
    GY: "Guyanais",
    HT: "Haïtien",
    HN: "Hondurien",
    HK: "Hongkongais",
    HU: "Hongrois",
    IS: "Islandais",
    IN: "Indien",
    ID: "Indonésien",
    IR: "Iranien",
    IQ: "Irakien",
    IE: "Irlandais",
    IL: "Israélien",
    IT: "Italien",
    JM: "Jamaïquain",
    JP: "Japonais",
    JO: "Jordanien",
    KZ: "Kazakhstanais",
    KE: "Kényan",
    KI: "Kiribatiens",
    KP: "Nord coréen",
    KR: "Sud coréen",
    KW: "Koweïtien",
    KG: "Kirghiz",
    LA: "Laotien",
    LV: "Letton",
    LB: "Libanais",
    LS: "Mosotho",
    LR: "Liberian",
    LY: "Libyen",
    LI: "Liechtensteinois",
    LT: "Lituanien",
    LU: "Luxembourgeois",
    MO: "Macanéen",
    MG: "Malgache",
    MW: "Malawien",
    MY: "Malaisien",
    MV: "Maldivien",
    ML: "Malien",
    MT: "Maltais",
    MH: "Marshallais",
    MQ: "Martiniquais",
    MR: "Mauritanien",
    MU: "Mauricien",
    YT: "Mahorais",
    MX: "Mexicain",
    FM: "Micronésien",
    MD: "Moldave",
    MC: "Monégasque",
    MN: "Mongol",
    MS: "Montserratien",
    MA: "Marocain",
    MZ: "Mozambicain",
    MM: "Birman",
    NA: "Namibien",
    NR: "Nauruan",
    NP: "Népalais",
    NL: "Néerlandais",
    NC: "Néo-Calédonien",
    NZ: "Néo-Zélandais",
    NI: "Nicaraguayen",
    NE: "Nigérien",
    NG: "Nigérian",
    NU: "Niuéen",
    NF: "Norfolkais",
    MK: "Macédonien",
    NO: "Norvégien",
    OM: "Omanais",
    PK: "Pakistanais",
    PW: "Palauan",
    PA: "Panaméen",
    PG: "Papouasien",
    PY: "Paraguayen",
    PE: "Péruvien",
    PH: "Philippin",
    PL: "Polonais",
    PT: "Portugais",
    PR: "Portoricain",
    QA: "Qatarien",
    RE: "Réunionnais",
    RO: "Roumain",
    RU: "Russe",
    RW: "Rwandais",
    SH: "Sainte Hélène",
    KN: "Afro-Kittitien et Afro-Nevisien",
    LC: "Saint-Lucien",
    PM: "Saint-Pierrais ou Miquelonais",
    VC: "Vincentais",
    WS: "Samoan",
    SM: "Saint-Marinais",
    ST: "Santoméen",
    SA: "Saoudien",
    SN: "Sénégalais",
    SC: "Seychellois",
    SL: "Sierra Léonais",
    SG: "Singapourien",
    SK: "Slovaque",
    SI: "Slovène",
    SB: "Salomonais",
    SO: "Somalien",
    ZA: "Sud Africain",
    ES: "Espagnol",
    LK: "Sri Lankais",
    SD: "Soudanais",
    SR: "Surinamais",
    SZ: "Swazi",
    SE: "Suédois",
    CH: "Suisse",
    SY: "Syrien",
    TW: "Taïwanais",
    TJ: "Tadjik",
    TZ: "Tanzanien",
    TH: "Thaïlandais",
    TL: "Est-Timorais",
    TG: "Togolais",
    TK: "Tokélaou",
    TO: "Tongien",
    TT: "Trinidadien ou Tobagonien",
    TN: "Tunisien",
    TR: "Turc",
    TM: "Turkmène",
    TC: "Îles Turques-et-Caïques",
    TV: "Tuvalais",
    UG: "Ougandais",
    UA: "Ukrainien",
    AE: "Émirien",
    GB: "Britannique",
    US: "Américain",
    UY: "Uruguayen",
    UZ: "Ouzbek",
    VU: "Vanuatais",
    VE: "Vénézuélien",
    VN: "Vietnamien",
    YE: "Yéménite",
    ZM: "Zambien",
    ZW: "Zimbabwéen",
    AX: "Îles Aland",
    BQ: "Pays-Bas Caribéens",
    CW: "Curacien",
    GG: "Guernesiais",
    IM: "Île de Man",
    JE: "Jersiais",
    ME: "Monténégrin",
    BL: "Saint-Barthélemy",
    MF: "Saint-Martinois (France)",
    RS: "Serbe",
    SX: "Saint-Martinois (Pays-Bas)",
    SS: "Sud-Soudanais",
    XK: "Kosovar",
};

const frenchNationalitiesFemale = {
    AF: "Afghane",
    AL: "Albanaise",
    DZ: "Algérienne",
    AD: "Andorrane",
    AO: "Angolaise",
    AG: "Antiguyenne",
    AR: "Argentine",
    AM: "Arménienne",
    AU: "Australienne",
    AT: "Autrichienne",
    AZ: "Azerbaïdjanaise",
    BS: "Bahamienne",
    BH: "Bahreïnienne",
    BD: "Bangladaise",
    BB: "Barbadienne",
    BY: "Biélorusse",
    BE: "Belge",
    BZ: "Bélizienne",
    BJ: "Béninoise",
    BM: "Bermudienne",
    BT: "Bhoutanaise",
    BO: "Bolivienne",
    BA: "Bosnienne",
    BW: "Botswanaise",
    BR: "Brésilienne",
    BN: "Brunéienne",
    BG: "Bulgare",
    BF: "Burkinabé",
    BI: "Burundaise",
    KH: "Cambodgienne",
    CM: "Camerounaise",
    CA: "Canadienne",
    CV: "Cap verdienne",
    KY: "Caïmanienne",
    CF: "Centrafricaine",
    TD: "Tchadienne",
    CL: "Chilienne",
    CN: "Chinoise",
    CO: "Colombienne",
    KM: "Comorienne",
    CG: "Congolaise (République du Congo)",
    CD: "Congolaise (République démocratique du Congo)",
    CR: "Costaricaine",
    CI: "Ivoirienne",
    HR: "Croate",
    CU: "Cubaine",
    CY: "Chypriote",
    CZ: "Tchèque",
    DK: "Danoise",
    DJ: "Djiboutienne",
    DM: "Dominicaine (Dominique)",
    DO: "Dominicaine (République dominicaine)",
    EC: "Équatorienne",
    EG: "Égyptienne",
    SV: "Salvadorienne",
    GQ: "Équato-guinéenne",
    ER: "Érythréenne",
    EE: "Estonienne",
    ET: "Éthiopienne",
    FK: "Malouine",
    FO: "Féroïenne",
    FJ: "Fidjienne",
    FI: "Finlandaise",
    FR: "Française",
    GF: "Française (Guyane)",
    PF: "Française (Polynésie française)",
    TF: "Française (TAAF)",
    GA: "Gabonaise",
    GM: "Gambienne",
    GE: "Géorgienne",
    DE: "Allemande",
    GH: "Ghanéenne",
    GI: "Gibraltariennes",
    GR: "Grecque",
    GL: "Groenlandaise",
    GD: "Grenadienne",
    GP: "Guadeloupéenne",
    GT: "Guatémaltèque",
    GN: "Guinéenne",
    GW: "Bissaoguinéenne",
    GY: "Guyanaise",
    HT: "Haïtienne",
    HN: "Hondurienne",
    HK: "Hongkongaise",
    HU: "Hongroise",
    IS: "Islandaise",
    IN: "Indienne",
    ID: "Indonésienne",
    IR: "Iranienne",
    IQ: "Irakienne",
    IE: "Irlandaise",
    IL: "Israélienne",
    IT: "Italienne",
    JM: "Jamaïquaine",
    JP: "Japonaise",
    JO: "Jordanienne",
    KZ: "Kazakhstanaise",
    KE: "Kényanne",
    KI: "Kiribatiennes",
    KP: "Nord coréenne",
    KR: "Sud coréenne",
    KW: "Koweïtienne",
    KG: "Kirghize",
    LA: "Laotienne",
    LV: "Lettonne",
    LB: "Libanaise",
    LS: "Mosotho",
    LR: "Liberienne",
    LY: "Libyenne",
    LI: "Liechtensteinoise",
    LT: "Lituanienne",
    LU: "Luxembourgeoise",
    MO: "Macanéenne",
    MG: "Malgache",
    MW: "Malawienne",
    MY: "Malaisienne",
    MV: "Maldivienne",
    ML: "Malienne",
    MT: "Maltaise",
    MH: "Marshallaise",
    MQ: "Martiniquaise",
    MR: "Mauritanienne",
    MU: "Mauricienne",
    YT: "Mahoraise",
    MX: "Mexicaine",
    FM: "Micronésienne",
    MD: "Moldave",
    MC: "Monégasque",
    MN: "Mongole",
    MS: "Montserratienne",
    MA: "Marocaine",
    MZ: "Mozambicaine",
    MM: "Birmane",
    NA: "Namibienne",
    NR: "Nauruane",
    NP: "Népalaise",
    NL: "Néerlandaise",
    NC: "Néo-Calédonienne",
    NZ: "Néo-Zélandaise",
    NI: "Nicaraguayenne",
    NE: "Nigérienne",
    NG: "Nigériane",
    NU: "Niuéenne",
    NF: "Norfolkaise",
    MK: "Macédonienne",
    NO: "Norvégienne",
    OM: "Omanaise",
    PK: "Pakistanaise",
    PW: "Palauane",
    PA: "Panaméenne",
    PG: "Papouasienne",
    PY: "Paraguayenne",
    PE: "Péruvienne",
    PH: "Philippine",
    PL: "Polonaise",
    PT: "Portugaise",
    PR: "Portoricaine",
    QA: "Qatarienne",
    RE: "Réunionnaise",
    RO: "Roumaine",
    RU: "Russe",
    RW: "Rwandaise",
    SH: "Sainte Hélène",
    KN: "Afro-Kittitienne et Afro-Nevisienne",
    LC: "Saint-Lucienne",
    PM: "Saint-Pierraise ou Miquelonaise",
    VC: "Vincentaise",
    WS: "Samoane",
    SM: "Saint-Marinaise",
    ST: "Santoméenne",
    SA: "Saoudienne",
    SN: "Sénégalaise",
    SC: "Seychelloise",
    SL: "Sierra Léonaise",
    SG: "Singapourienne",
    SK: "Slovaque",
    SI: "Slovène",
    SB: "Salomonaise",
    SO: "Somalienne",
    ZA: "Sud Africaine",
    ES: "Espagnole",
    LK: "Sri Lankaise",
    SD: "Soudanaise",
    SR: "Surinamaise",
    SZ: "Swazie",
    SE: "Suédoise",
    CH: "Suisse",
    SY: "Syrienne",
    TW: "Taïwanaise",
    TJ: "Tadjike",
    TZ: "Tanzanienne",
    TH: "Thaïlandaise",
    TL: "Est-Timoraise",
    TG: "Togolaise",
    TK: "Tokélaouane",
    TO: "Tongienne",
    TT: "Trinidadienne ou Tobagonienne",
    TN: "Tunisienne",
    TR: "Turque",
    TM: "Turkmène",
    TC: "Îles Turques-et-Caïques",
    TV: "Tuvaluaise",
    UG: "Ougandaise",
    UA: "Ukrainienne",
    AE: "Émirienne",
    GB: "Britannique",
    US: "Américaine",
    UY: "Uruguayenne",
    UZ: "Ouzbèke",
    VU: "Vanuataise",
    VE: "Vénézuélienne",
    VN: "Vietnamienne",
    YE: "Yéménite",
    ZM: "Zambienne",
    ZW: "Zimbabwéenne",
    AX: "Îles Aland",
    BQ: "Pays-Bas Caribéens",
    CW: "Curacienne",
    GG: "Guernesaise",
    IM: "Île de Man",
    JE: "Jersaise",
    ME: "Monténégrine",
    BL: "Saint-Barthélemy",
    MF: "Saint-Martinoise (France)",
    RS: "Serbe",
    SX: "Saint-Martinoise (Pays-Bas)",
    SS: "Sud-Soudanaise",
    XK: "Kosovare",
};

const englishNationalities = {
    AF: "Afghan",
    AL: "Albanian",
    DZ: "Algerian",
    AD: "Andorran",
    AO: "Angolan",
    AG: "Antiguans",
    AR: "Argentinean",
    AM: "Armenian",
    AU: "Australian",
    AT: "Austrian",
    AZ: "Azerbaijani",
    BS: "Bahamian",
    BH: "Bahraini",
    BD: "Bangladeshi",
    BB: "Barbadian",
    BY: "Belarusian",
    BE: "Belgian",
    BZ: "Belizean",
    BJ: "Beninese",
    BT: "Bhutanese",
    BO: "Bolivian",
    BA: "Bosnian - Herzegovinian",
    BW: "Batswana",
    BR: "Brazilian",
    BN: "Bruneian",
    BG: "Bulgarian",
    BF: "Burkinabe",
    BI: "Burundian",
    KH: "Cambodian",
    CM: "Cameroonian",
    CA: "Canadian",
    CV: "Cape Verdean",
    CF: "Central African",
    TD: "Chadian",
    CL: "Chilean",
    CN: "Chinese",
    CO: "Colombian",
    KM: "Comoran",
    CG: "Congolese (Republic of the Congo)",
    CD: "Congolese (Democratic Republic of the Congo)",
    CR: "Costa Rican",
    CI: "Ivorian",
    HR: "Croatian",
    CU: "Cuban",
    CY: "Cypriot",
    CZ: "Czech",
    DK: "Danish",
    DM: "Dominican (Dominica)",
    DO: "Dominican (Dominican Republic)",
    EC: "Ecuadorean",
    EG: "Egyptian",
    SV: "Salvadoran",
    GQ: "Equatorial Guinean",
    ER: "Eritrean",
    EE: "Estonian",
    ET: "Ethiopian",
    FJ: "Fijian",
    FI: "Finnish",
    FR: "French",
    GA: "Gabonese",
    GM: "Gambian",
    GE: "Georgian",
    DE: "German",
    GH: "Ghanaian",
    GR: "Greek",
    GD: "Grenadian",
    GT: "Guatemalan",
    GN: "Guinean",
    GW: "Guinea-Bissauan",
    GY: "Guyanese",
    HT: "Haitian",
    HN: "Honduran",
    HU: "Hungarian",
    IS: "Icelandic",
    IN: "Indian",
    ID: "Indonesian",
    IR: "Iranian",
    IQ: "Iraqi",
    IE: "Irish",
    IL: "Israeli",
    IT: "Italian",
    JM: "Jamaican",
    JP: "Japanese",
    JO: "Jordanian",
    KZ: "Kazakhstani",
    KE: "Kenyan",
    KI: "I-Kiribati",
    KP: "North Korean",
    KR: "South Korean",
    KW: "Kuwaiti",
    KG: "Kyrgyz",
    LA: "Laotian",
    LV: "Latvian",
    LB: "Lebanese",
    LS: "Mosotho",
    LR: "Liberian",
    LY: "Libyan",
    LI: "Liechtensteiner",
    LT: "Lithuanian",
    LU: "Luxembourger",
    MG: "Malagasy",
    MW: "Malawian",
    MY: "Malaysian",
    MV: "Maldivan",
    ML: "Malian",
    MT: "Maltese",
    MH: "Marshallese",
    MR: "Mauritanian",
    MU: "Mauritian",
    MX: "Mexican",
    FM: "Micronesian",
    MD: "Moldovan",
    MC: "Monacan",
    MN: "Mongolian",
    MA: "Moroccan",
    MZ: "Mozambican",
    MM: "Burmese",
    NA: "Namibian",
    NR: "Nauruan",
    NP: "Nepalese",
    NL: "Dutch",
    NZ: "New Zealander",
    NI: "Nicaraguan",
    NE: "Nigerien",
    NG: "Nigerian",
    MK: "Macedonian",
    NO: "Norwegian",
    OM: "Omani",
    PK: "Pakistani",
    PW: "Palauan",
    PA: "Panamanian",
    PY: "Paraguayan",
    PE: "Peruvian",
    PH: "Filipino",
    PL: "Polish",
    PT: "Portuguese",
    QA: "Qatari",
    RO: "Romanian",
    RU: "Russian",
    RW: "Rwandan",
    KN: "Kittian and Nevisian",
    LC: "Saint Lucian",
    VC: "Saint Vincent and the Grenadines",
    WS: "Samoan",
    SM: "San Marinese",
    ST: "Sao Tomean",
    SA: "Saudi",
    SN: "Senegalese",
    SC: "Seychellois",
    SL: "Sierra Leonean",
    SG: "Singaporean",
    SK: "Slovakian",
    SI: "Slovenian",
    SB: "Solomon Islander",
    SO: "Somali",
    ZA: "South African",
    ES: "Spanish",
    LK: "Sri Lankan",
    SD: "Sudanese",
    SR: "Surinamer",
    SZ: "Swazi",
    SE: "Swedish",
    CH: "Swiss",
    SY: "Syrian",
    TW: "Taiwanese",
    TJ: "Tajik",
    TZ: "Tanzanian",
    TH: "Thai",
    TL: "East Timorese",
    TG: "Togolese",
    TO: "Tongan",
    TT: "Trinidadian or Tobagonian",
    TN: "Tunisian",
    TR: "Turkish",
    TV: "Tuvaluan",
    UG: "Ugandan",
    UA: "Ukrainian",
    AE: "Emirian",
    GB: "British",
    US: "American",
    UY: "Uruguayan",
    UZ: "Uzbekistani",
    VE: "Venezuelan",
    VN: "Vietnamese",
    YE: "Yemenite",
    ZM: "Zambian",
    ZW: "Zimbabwean",
    ME: "Montenegrin",
    RS: "Serbian",
    SS: "South Sudan",
    XK: "Kosovo",
};

export const getNationality = (
    countryCode: string,
    language: string,
    gender = "m"
) => {
    countryCode = countryCode.toUpperCase();

    if (language === "en") {
        return englishNationalities[
            countryCode as keyof typeof englishNationalities
        ];
    }

    if (language === "fr") {
        return gender === "f"
            ? frenchNationalitiesFemale[
                  countryCode as keyof typeof frenchNationalitiesFemale
              ]
            : frenchNationalitiesMale[
                  countryCode as keyof typeof frenchNationalitiesMale
              ];
    }

    throw new Error('Language must be "fr" or "en"');
};
