export const RoutesList = {
    Index: "",
    Login: "login",
    AdminUsers: "users",
    AdminHome: "home",
    AdminLogs: "logs",
    AdminJobs: "jobs",
    NotFound: "not-found",
    AdminActivityLogs: "activity-logs",
    AdminKeyValues: "key-values",
    RecoverPassword: "recover-password",
    AdminTest: "admin-test",
    AdminLiveTracking: "live-tracking",
    AdminRoles: "roles",
    AdminAppTypes: "app-types",
    CandidatesList: "candidats",
    CandidateEdit: "candidat",
    CandidateApplicationsList: "candidatures",
    CandidateApplyForm: "formulaire-de-candidature",
    Customers: "clients",
    JobOffers: "offres-emplois",
    CandidateRefApplyForm: "formulaire-de-candidature-ref",
    Messaging: "messagerie",
    JobReferences: "references",
    JobReferencesDetails: "references-details",
    Newsletters: "newsletters",
    InterviewsManage: "interview-manage",
    Interviews: "interviews",
    UnsubscribeNewsletter: "unsubscribe-newsletter",

    // Candidate section
    Candidate_MyApplications: "mes-candidatures",
    Candidate_MyDossier: "mon-dossier",
    Candidate_MyMmiResume: "mon-cv-mmi",
    Candidate_MmiAndMe: "mmi-et-moi",
    MatchCandidateJobOffer: "match-candidate-jobOffer",
    Candidate_MyDashBoard: "mon-tableau-de-bord",
    AnonymousExchange: "echanges",
    AdminMailsTests: "mails-tests",
};
