/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppValueDto } from './appValueDto';
import { TranslationDto } from './translationDto';


export interface AppTypeDto { 
    id?: string;
    label: string;
    code: string;
    appValues: Array<AppValueDto>;
    translations?: Array<TranslationDto>;
}

