/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExperienceFamilyChildDto } from './experienceFamilyChildDto';
import { CandidateResumeDto } from './candidateResumeDto';
import { AppValueDto } from './appValueDto';


export interface CandidateResumeExperienceDto { 
    id?: string;
    creationDate?: Date;
    modifDate?: Date;
    experienceEndDate?: Date;
    experienceStartDate?: Date;
    experienceEndDateString?: string;
    experienceStartDateString?: string;
    postTitle?: string;
    postDescription?: string;
    postResponsability?: string;
    candidateResumeId?: string;
    candidateResume?: CandidateResumeDto;
    employerProfileId?: string;
    employerProfile?: AppValueDto;
    child?: Array<ExperienceFamilyChildDto>;
    leavingReason?: string;
    city?: string;
    country?: string;
    currentlyInPosition?: boolean;
    currentlyInPositionStr?: string;
}

