/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidateDto } from './candidateDto';
import { AppValueDto } from './appValueDto';


export interface CandidateLicenceDto { 
    id?: string;
    candidate?: CandidateDto;
    candidateId?: string;
    licence?: AppValueDto;
    licenceId?: string;
    countryCode?: string;
}

