/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidateResumeDto } from './candidateResumeDto';


export interface CandidateResumeFormationDto { 
    id?: string;
    creationDate?: Date;
    modifDate?: Date;
    formationStartYear?: number;
    formationStartMonth?: number;
    formationStartMonthString?: string;
    formationEndYear?: number;
    formationEndMonth?: number;
    formationEndMonthString?: string;
    formationDiplomeName?: string;
    place?: string;
    school?: string;
    candidateResumeId?: string;
    candidateResume?: CandidateResumeDto;
}

