/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetCandidatesRequest { 
    /**
     * The start of the request
     */
    start?: number;
    /**
     * The length of the request
     */
    length?: number;
    /**
     * order by field
     */
    orderby?: string;
    /**
     * order direction (asc | desc)
     */
    order?: string;
    /**
     * Search
     */
    search?: string;
    /**
     * filter candidates with a specific status
     */
    candidateStatut?: string;
    /**
     * filter candidates by jobs
     */
    jobIds?: string;
    /**
     * filter candidates by gender
     */
    candidateGender?: string;
    /**
     * filter candidates by nationality
     */
    candidateNationality?: string;
    /**
     * set filter candidates min age
     */
    candidateMinYear?: string;
    /**
     * set filter candidates max age
     */
    candidateMaxYear?: string;
    /**
     * filter candidates by job housed criteria
     */
    jobHoused?: string;
    /**
     * filter candidates with driver licence
     */
    driverLicence?: string;
    /**
     * filter candidates mobility countries
     */
    mobilityCountries?: string;
    /**
     * filter candidates mobility departments
     */
    mobilityDepartments?: string;
    /**
     * filter candidates children min age
     */
    childrenMinAge?: string;
    /**
     * filter candidates children max age
     */
    childrenMaxAge?: string;
    /**
     * filter candidates by pets
     */
    pets?: string;
    /**
     * filter candidates with contract type
     */
    contractType?: string;
    /**
     * filter candidates if available or not
     */
    isAvailable?: string;
    /**
     * filter candidates by location
     */
    candidateLocation?: string;
    /**
     * filter candidates by licences
     */
    licencesIds?: string;
    /**
     * filter candidates by language
     */
    languagesIds?: string;
    /**
     * include percentage advancement dossier ? true or false
     */
    includePercentageAdvancement?: string;
    /**
     * filter by disabled
     */
    disabled?: string;
    /**
     * search candidate by cities
     */
    city?: Array<string>;
    /**
     * search candidate by department
     */
    department?: string;
    /**
     * filter candidates if vehicle or not
     */
    isVehicle?: string;
    /**
     * get candidate by consultants
     */
    consultantIds?: string;
    /**
     * include candidates without assigned consultant when filtering by consultantIds
     */
    includeUnassignedCandidates?: string;
    /**
     * filter candidates by ids from references
     */
    candidateIdsFromReferences?: string;
    /**
     * languages
     */
    languages?: Array<object>;
    /**
     * filter candidates if have global mobility or not
     */
    globalMobility?: string;
    /**
     * get candidate by note
     */
    note?: number;
    /**
     * get candidate by travel
     */
    hasManyTravel?: string;
}

