/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserConnectionsByPM2App } from './userConnectionsByPM2App';


export interface GetUserConnectionsWrapperResponse { 
    success: boolean;
    message?: string;
    error?: object;
    statusCode?: number;
    errorGuid?: string;
    token?: string;
    connectionsWrapper: Array<UserConnectionsByPM2App>;
    currentPm2AppId: number;
}

