/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteItemFileDto } from './noteItemFileDto';
import { UserDto } from './userDto';
import { CandidateDto } from './candidateDto';


export interface NoteItemDto { 
    id?: string;
    creationDate?: Date;
    modifDate?: Date;
    content?: string;
    consultant?: UserDto;
    consultantId?: string;
    candidateId?: string;
    candidate?: CandidateDto;
    files?: Array<NoteItemFileDto>;
}

