/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidateDto } from './candidateDto';


export interface SaveCandidateRequest { 
    specificRelations?: string;
    includeFiles?: string;
    includeLicences?: string;
    includeAddresses?: string;
    includeNoteItems?: string;
    includeCandidateJobs?: string;
    includeLanguages?: string;
    includeChildren?: string;
    includeResume?: string;
    includeConsultant?: string;
    includePets?: string;
    includeContracts?: string;
    includeCountries?: string;
    includeDepartments?: string;
    includeCurrentJobs?: string;
    includeBasicInformations?: string;
    candidate: CandidateDto;
}

