/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCandidateJobStatusDto { 
    candidateJobId?: string;
    status?: UpdateCandidateJobStatusDto.StatusEnum;
}
export namespace UpdateCandidateJobStatusDto {
    export type StatusEnum = 'VALIDATED' | 'REFUSED' | 'PENDING';
    export const StatusEnum = {
        Validated: 'VALIDATED' as StatusEnum,
        Refused: 'REFUSED' as StatusEnum,
        Pending: 'PENDING' as StatusEnum
    };
}


