/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleDto } from './userRoleDto';
import { LanguageDto } from './languageDto';
import { AppFileDto } from './appFileDto';
import { CandidateDto } from './candidateDto';
import { AppValueDto } from './appValueDto';
import { TranslationDto } from './translationDto';


export interface UserDto { 
    id?: string;
    creationDate?: Date;
    modifDate?: Date;
    disabled?: boolean;
    userName: string;
    password?: string;
    roles?: Array<UserRoleDto>;
    rolesString?: Array<string>;
    mail?: string;
    phone?: string;
    phoneFix?: string;
    pushSubscriptions?: Array<string>;
    languageId?: string;
    language?: LanguageDto;
    presentation?: string;
    translations?: Array<TranslationDto>;
    firstName?: string;
    lastName?: string;
    facebookUserId?: string;
    googleUserId?: string;
    image?: AppFileDto;
    imageId?: string;
    recoverToken?: string;
    recoverTokenExpirationDate?: Date;
    refreshToken?: string;
    candidate?: CandidateDto;
    candidateId?: string;
    genderId?: string;
    gender?: AppValueDto;
    TOSAccepted?: boolean;
    loginToken?: string;
}

