/**
 * Morgan And Mallet CRM
 * Morgan And Mallet CRM API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidateCandidateApplicationRequest { 
    /**
     * candidate application id
     */
    id: string;
    /**
     * candidate current job
     */
    candidateCurrentJobIds?: Array<string>;
    /**
     * give ats access
     */
    giveAtsAccess?: boolean;
    /**
     * candidate gender id
     */
    genderId?: string;
}

